<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        /**
         * async function aaa(){} 
         * 1. async 用户标识函数的，async函数返回的结果就是一个promise
         * 2. 方法正常，返回的value就是成功后的return值
         * 3. 方法中出现了异常 则返回的是promise就是一个失败状态
         * 4. async函数返回的结果如果是一个promise 则状态由内部的promise决定
         */
        // let f1 = async () => {
        //     // return 10
        //     // throw new Error("something wrong")
        //     let promise = Promise.reject("HHHH")
        //     return promise
        // }
        // let promise = f1()
        // promise.then(
        //     function (value) {
        //         console.log("success " + value)
        //     }
        // ).catch(
        //     function (value) {
        //         console.log("fail " + value)

        //     }
        // )
        /**
         * await 帮助我们获取promise成功状态的返回值的关键字
         * 1. await 右边是一个普通的值 则直接返回该值 如果右边是promise 返回promise成功的状态
         * 2. await 右边如果是一个失败状态的promise 那么await会直接抛出异常
         * 3. await 关键字必须在async修饰的函数中使用，async函数中可以没有await
         * 4. await 后面的代码会等待await执行完毕继续执行
         * 
        */
        async function fun1() {
            return 10
        }
        async function fun2() {
            let res = await fun1()
            
            // let res = Promise.reject("someting error")
            console.log("await got " + res)
        }
        fun2()



    </script>
</head>

<body>

</body>

</html>